-- Seed data: AY 2026-2027 roster + block schedule. Run AFTER schema.sql.
begin;
delete from assignments; delete from requests; delete from residents; delete from blocks;

insert into blocks (block_no,start_date,end_date) values
  (1,'2026-07-01','2026-07-26'),
  (2,'2026-07-27','2026-08-23'),
  (3,'2026-08-24','2026-09-20'),
  (4,'2026-09-21','2026-10-18'),
  (5,'2026-10-19','2026-11-15'),
  (6,'2026-11-16','2026-12-13'),
  (7,'2026-12-14','2027-01-10'),
  (8,'2027-01-11','2027-02-07'),
  (9,'2027-02-08','2027-03-07'),
  (10,'2027-03-08','2027-04-04'),
  (11,'2027-04-05','2027-05-02'),
  (12,'2027-05-03','2027-05-30'),
  (13,'2027-05-31','2027-06-30');

insert into residents (full_name,sched_key,pgy,clinic_cohort) values
  ('Delaney Abood','Abood, D',1,null),
  ('Nabiha Ahmed','Ahmed, N',1,'CCTHA'),
  ('Iman Ashraf','Ashraf, I',1,'CCTHA'),
  ('Kimia Badakhshan','Badakhshan, K',1,'CCMA'),
  ('Hima Chakka','Chakka, H',1,'CCTUA'),
  ('Mariana Dajac','Dajac, M',1,'CCWA'),
  ('Suzete Farias Da Guarda','Farias Da Guarda, S',1,null),
  ('Richard Gammill','Gammill, R',1,'CCMA'),
  ('Rea Haugen','Haugen, R',1,'CCTHA'),
  ('Anne Humm','Humm, A',1,null),
  ('Abhinav Kari','Kari, A',1,'CCTHA'),
  ('Gabrielle Lutz','Lutz, G',1,'CCWA'),
  ('Madison McInnis','McInnis, M',1,'CCWA'),
  ('Raina Modi','Modi, R',1,'CCTUA'),
  ('Gabriel Morales','Morales, G',1,null),
  ('Carter Olberding','Olberding, C',1,'CCTUA'),
  ('Neel Patel','Patel, N',1,'CCMA'),
  ('Sonia Patel','Patel, S',1,'CCWA'),
  ('Alejandro Perez','Perez, A',1,null),
  ('Tianna Sasher','Sasher, T',1,null),
  ('Alison Todd','Todd, A',1,'CCTHA'),
  ('Tatiana Wirth','Wirth, T',1,'CCTUA'),
  ('Nicolette Casarcia','Casarcia, N',2,'CCTHA'),
  ('Barrie Clark','Clark, B',2,'CCTHA'),
  ('Gregory Collins','Collins, G',2,'CCTHA'),
  ('Ryan Daniel','Daniel, R',2,'CCWA'),
  ('Connor Dyer','Dyer, N',2,'CCWA'),
  ('Shirley Gandhi','Gandhi, S',2,'CCTUA'),
  ('Sydney Hicks','Hicks, S',2,'CCTUA'),
  ('Gaurav Kiri','Kiri, G',2,'CCWA'),
  ('Riya Kumar','Kumar, R',2,'CCTUA'),
  ('Danielle Mason','Mason, D',2,'CCMA'),
  ('Laura Osherov','Osherov, L',2,'CCMA'),
  ('Elizabeth Pierce','Pierce, E',2,'CCMA'),
  ('Ashley Stiglich','Stiglich, A',2,'CCMA'),
  ('Jacob Theriault','Theriault, J',2,'CCMA'),
  ('Brooke Wilson','Wilson, B',2,'CCTUA'),
  ('Brianna Woodbeck','Woodbeck, B',2,'CCWA'),
  ('Claudia Aleman Oliva','Aleman Oliva, C',3,'CCTHA'),
  ('Hamza Choudhry','Choudhry, H',3,'CCTHA'),
  ('Alexis Chrystman','Chrystman, A',3,'CCWA'),
  ('Alexander den Boef','den Boef, A',3,'CCTHA'),
  ('Parth Desai','Desai, P',3,'CCWA'),
  ('Julie Gaudin','Gaudin, J',3,'CCWA'),
  ('Austin Haley','Haley, A',3,'CCWA'),
  ('Nathan Heathcoat','Heathcoat, N',3,'CCTUA'),
  ('Guillermo Loyola','Loyola, G',3,'CCTUA'),
  ('Ty Merry','Merry, T',3,'CCTUA'),
  ('Sneh Parekh','Parekh, S',3,null),
  ('Phillip Petrasko','Petrasko, P',3,null),
  ('Zehra Rahman','Rahman, Z',3,null),
  ('Yasasvhinie Santharam','Santharam, Y',3,null),
  ('Tiffany Scotto','Scotto, T',3,null),
  ('Shelby Watford','Watford, S (PRG3)',3,null);

insert into assignments (resident_id,block_no,cell) values
  ((select id from residents where sched_key='Abood, D'),1,'MED B'),
  ((select id from residents where sched_key='Abood, D'),2,'CCU'),
  ((select id from residents where sched_key='Abood, D'),3,'AMB (8/24 - 9/6) || MED D (9/7 - 9/20)'),
  ((select id from residents where sched_key='Abood, D'),4,'NEPH CONS (9/21 - 10/4) || VACATION (9/28 - 10/2) || NF (10/5 - 10/18)'),
  ((select id from residents where sched_key='Abood, D'),5,'MED B'),
  ((select id from residents where sched_key='Abood, D'),6,'ID CONSULT || VACATION (11/23 - 11/27)'),
  ((select id from residents where sched_key='Abood, D'),7,'MICU B'),
  ((select id from residents where sched_key='Abood, D'),8,'MED C'),
  ((select id from residents where sched_key='Abood, D'),9,'CV CONSULTS || VACATION (2/15 - 2/19)'),
  ((select id from residents where sched_key='Abood, D'),10,'MED C'),
  ((select id from residents where sched_key='Abood, D'),11,'GENERAL NEURO'),
  ((select id from residents where sched_key='Abood, D'),12,'MICU B'),
  ((select id from residents where sched_key='Abood, D'),13,'GENERAL NEURO'),
  ((select id from residents where sched_key='Ahmed, N'),1,'MED D'),
  ((select id from residents where sched_key='Ahmed, N'),2,'GI CONSULT (7/27 - 8/9) || VACATION (8/3 - 8/7) || NF (8/10 - 8/23)'),
  ((select id from residents where sched_key='Ahmed, N'),3,'MED A'),
  ((select id from residents where sched_key='Ahmed, N'),4,'ED MED'),
  ((select id from residents where sched_key='Ahmed, N'),5,'MED C'),
  ((select id from residents where sched_key='Ahmed, N'),6,'CCU'),
  ((select id from residents where sched_key='Ahmed, N'),7,'IM CONS'),
  ((select id from residents where sched_key='Ahmed, N'),8,'CCU'),
  ((select id from residents where sched_key='Ahmed, N'),9,'MED B'),
  ((select id from residents where sched_key='Ahmed, N'),10,'GENERAL NEURO || VACATION (3/15 - 3/19)'),
  ((select id from residents where sched_key='Ahmed, N'),11,'ID CONSULT (4/5 - 4/18) || NF (4/19 - 5/2)'),
  ((select id from residents where sched_key='Ahmed, N'),12,'AMB || VACATION (5/3 - 5/7)'),
  ((select id from residents where sched_key='Ahmed, N'),13,'MICU B'),
  ((select id from residents where sched_key='Ashraf, I'),1,'GENERAL NEURO'),
  ((select id from residents where sched_key='Ashraf, I'),2,'MED A'),
  ((select id from residents where sched_key='Ashraf, I'),3,'CCU'),
  ((select id from residents where sched_key='Ashraf, I'),4,'MED A'),
  ((select id from residents where sched_key='Ashraf, I'),5,'ED MED || VACATION (10/26 - 10/30)'),
  ((select id from residents where sched_key='Ashraf, I'),6,'MED C'),
  ((select id from residents where sched_key='Ashraf, I'),7,'MICU C'),
  ((select id from residents where sched_key='Ashraf, I'),8,'AMB'),
  ((select id from residents where sched_key='Ashraf, I'),9,'MED D'),
  ((select id from residents where sched_key='Ashraf, I'),10,'IM CONS || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Ashraf, I'),11,'NF (4/5 - 4/17) || ID CONSULT (4/18 - 5/2) || VACATION (4/19 - 4/23)'),
  ((select id from residents where sched_key='Ashraf, I'),12,'MICU C'),
  ((select id from residents where sched_key='Ashraf, I'),13,'ONC CONSULT (5/31 - 6/13) || CCU (6/14 - 6/30)'),
  ((select id from residents where sched_key='Badakhshan, K'),1,'MED D'),
  ((select id from residents where sched_key='Badakhshan, K'),2,'MICU B'),
  ((select id from residents where sched_key='Badakhshan, K'),3,'ED MED'),
  ((select id from residents where sched_key='Badakhshan, K'),4,'CCU'),
  ((select id from residents where sched_key='Badakhshan, K'),5,'MED A'),
  ((select id from residents where sched_key='Badakhshan, K'),6,'GENERAL NEURO || VACATION (11/23 - 11/27)'),
  ((select id from residents where sched_key='Badakhshan, K'),7,'MED C'),
  ((select id from residents where sched_key='Badakhshan, K'),8,'GI CONSULT (1/11 - 1/24) || NF (1/25 - 2/7)'),
  ((select id from residents where sched_key='Badakhshan, K'),9,'IM CONS || VACATION (2/15 - 2/19)'),
  ((select id from residents where sched_key='Badakhshan, K'),10,'CCU'),
  ((select id from residents where sched_key='Badakhshan, K'),11,'AMB || VACATION (4/26 - 4/30)'),
  ((select id from residents where sched_key='Badakhshan, K'),12,'MED A'),
  ((select id from residents where sched_key='Badakhshan, K'),13,'MED A'),
  ((select id from residents where sched_key='Chakka, H'),1,'AMB'),
  ((select id from residents where sched_key='Chakka, H'),2,'IM CONS'),
  ((select id from residents where sched_key='Chakka, H'),3,'MED A'),
  ((select id from residents where sched_key='Chakka, H'),4,'GENERAL NEURO || VACATION (10/5 - 10/9)'),
  ((select id from residents where sched_key='Chakka, H'),5,'MED C'),
  ((select id from residents where sched_key='Chakka, H'),6,'CCU'),
  ((select id from residents where sched_key='Chakka, H'),7,'ED MED'),
  ((select id from residents where sched_key='Chakka, H'),8,'MED B'),
  ((select id from residents where sched_key='Chakka, H'),9,'MICU B'),
  ((select id from residents where sched_key='Chakka, H'),10,'NF (3/8 - 3/21) || GI CONSULT (3/22 - 4/4) || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Chakka, H'),11,'MED C'),
  ((select id from residents where sched_key='Chakka, H'),12,'MED A'),
  ((select id from residents where sched_key='Chakka, H'),13,'ONC CONSULT (5/31 - 6/13) || VACATION (6/7 - 6/11) || NF (6/14 - 6/30)'),
  ((select id from residents where sched_key='Dajac, M'),1,'MICU A'),
  ((select id from residents where sched_key='Dajac, M'),2,'MED B'),
  ((select id from residents where sched_key='Dajac, M'),3,'AMB'),
  ((select id from residents where sched_key='Dajac, M'),4,'ED MED'),
  ((select id from residents where sched_key='Dajac, M'),5,'CCU'),
  ((select id from residents where sched_key='Dajac, M'),6,'IM CONS || VACATION (11/23 - 11/27)'),
  ((select id from residents where sched_key='Dajac, M'),7,'MED B'),
  ((select id from residents where sched_key='Dajac, M'),8,'NF (1/11 - 1/24) || NEPH CONS (1/25 - 2/7) || VACATION (2/1 - 2/5)'),
  ((select id from residents where sched_key='Dajac, M'),9,'MED A'),
  ((select id from residents where sched_key='Dajac, M'),10,'GI CONSULT (3/8 - 3/21) || AMB (3/22 - 4/4)'),
  ((select id from residents where sched_key='Dajac, M'),11,'MED C'),
  ((select id from residents where sched_key='Dajac, M'),12,'GENERAL NEURO || VACATION (5/17 - 5/21)'),
  ((select id from residents where sched_key='Dajac, M'),13,'CCU'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),1,'MICU B'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),2,'MED D'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),3,'GENERAL NEURO'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),4,'MED C'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),5,'NF (10/19 - 11/1) || ID CONSULT (11/2 - 11/15) || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),6,'MICU B'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),7,'CV CONSULTS (12/14 - 12/27) || NF (12/28 - 1/10)'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),8,'MED D'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),9,'GI CONSULT || VACATION (3/1 - 3/5)'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),10,'MED D'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),11,'CCU'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),12,'MED B'),
  ((select id from residents where sched_key='Farias Da Guarda, S'),13,'GENERAL NEURO || VACATION (6/21 - 6/25)'),
  ((select id from residents where sched_key='Gammill, R'),1,'IM CONS'),
  ((select id from residents where sched_key='Gammill, R'),2,'MED A'),
  ((select id from residents where sched_key='Gammill, R'),3,'CCU'),
  ((select id from residents where sched_key='Gammill, R'),4,'AMB || VACATION (9/28 - 10/2)'),
  ((select id from residents where sched_key='Gammill, R'),5,'MICU B'),
  ((select id from residents where sched_key='Gammill, R'),6,'NF (11/16 - 11/29) || ONC CONSULT (11/30 - 12/13)'),
  ((select id from residents where sched_key='Gammill, R'),7,'MED D'),
  ((select id from residents where sched_key='Gammill, R'),8,'ED MED'),
  ((select id from residents where sched_key='Gammill, R'),9,'MED A'),
  ((select id from residents where sched_key='Gammill, R'),10,'GENERAL NEURO || VACATION (3/15 - 3/19)'),
  ((select id from residents where sched_key='Gammill, R'),11,'MED A'),
  ((select id from residents where sched_key='Gammill, R'),12,'MICU D'),
  ((select id from residents where sched_key='Gammill, R'),13,'ID CONSULT || VACATION (5/31 - 6/4)'),
  ((select id from residents where sched_key='Haugen, R'),1,'MED A'),
  ((select id from residents where sched_key='Haugen, R'),2,'ED MED || VACATION (8/17 - 8/21)'),
  ((select id from residents where sched_key='Haugen, R'),3,'MED B'),
  ((select id from residents where sched_key='Haugen, R'),4,'CCU'),
  ((select id from residents where sched_key='Haugen, R'),5,'AMB || VACATION (11/9 - 11/13)'),
  ((select id from residents where sched_key='Haugen, R'),6,'MICU C'),
  ((select id from residents where sched_key='Haugen, R'),7,'GENERAL NEURO'),
  ((select id from residents where sched_key='Haugen, R'),8,'MED C'),
  ((select id from residents where sched_key='Haugen, R'),9,'CCU'),
  ((select id from residents where sched_key='Haugen, R'),10,'IM CONS || VACATION (3/15 - 3/19)'),
  ((select id from residents where sched_key='Haugen, R'),11,'MICU B'),
  ((select id from residents where sched_key='Haugen, R'),12,'GI CONSULT (5/3 - 5/16) || NF (5/17 - 5/30)'),
  ((select id from residents where sched_key='Haugen, R'),13,'MED B'),
  ((select id from residents where sched_key='Humm, A'),1,'GENERAL NEURO'),
  ((select id from residents where sched_key='Humm, A'),2,'ID CONSULT || VACATION (8/10 - 8/14)'),
  ((select id from residents where sched_key='Humm, A'),3,'MED C'),
  ((select id from residents where sched_key='Humm, A'),4,'MED D'),
  ((select id from residents where sched_key='Humm, A'),5,'GI CONSULT || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Humm, A'),6,'MED C'),
  ((select id from residents where sched_key='Humm, A'),7,'NF (12/14 - 12/27) || ONC CONSULT (12/28 - 1/10)'),
  ((select id from residents where sched_key='Humm, A'),8,'CV CONSULTS'),
  ((select id from residents where sched_key='Humm, A'),9,'MICU C'),
  ((select id from residents where sched_key='Humm, A'),10,'MED A'),
  ((select id from residents where sched_key='Humm, A'),11,'NEPH CONS'),
  ((select id from residents where sched_key='Humm, A'),12,'CV CONSULTS'),
  ((select id from residents where sched_key='Humm, A'),13,'GENERAL NEURO || VACATION (5/31 - 6/4)'),
  ((select id from residents where sched_key='Kari, A'),1,'CCU'),
  ((select id from residents where sched_key='Kari, A'),2,'MED C'),
  ((select id from residents where sched_key='Kari, A'),3,'GENERAL NEURO (8/24 - 9/6) || NF (9/7 - 9/20)'),
  ((select id from residents where sched_key='Kari, A'),4,'IM CONS || VACATION (9/28 - 10/2)'),
  ((select id from residents where sched_key='Kari, A'),5,'MICU C'),
  ((select id from residents where sched_key='Kari, A'),6,'MED A'),
  ((select id from residents where sched_key='Kari, A'),7,'AMB'),
  ((select id from residents where sched_key='Kari, A'),8,'MED B'),
  ((select id from residents where sched_key='Kari, A'),9,'ED MED || VACATION (2/22 - 2/26)'),
  ((select id from residents where sched_key='Kari, A'),10,'MED A'),
  ((select id from residents where sched_key='Kari, A'),11,'MICU C'),
  ((select id from residents where sched_key='Kari, A'),12,'MED C'),
  ((select id from residents where sched_key='Kari, A'),13,'GENERAL NEURO (5/31 - 6/13) || VACATION (6/7 - 6/11) || AMB (6/14 - 6/30)'),
  ((select id from residents where sched_key='Lutz, G'),1,'MICU C'),
  ((select id from residents where sched_key='Lutz, G'),2,'ED MED'),
  ((select id from residents where sched_key='Lutz, G'),3,'MED B'),
  ((select id from residents where sched_key='Lutz, G'),4,'MED C'),
  ((select id from residents where sched_key='Lutz, G'),5,'GI CONSULT (10/19 - 11/1) || VACATION (10/19 - 10/23) || NF (11/2 - 11/15)'),
  ((select id from residents where sched_key='Lutz, G'),6,'GENERAL NEURO'),
  ((select id from residents where sched_key='Lutz, G'),7,'MICU D'),
  ((select id from residents where sched_key='Lutz, G'),8,'MED A'),
  ((select id from residents where sched_key='Lutz, G'),9,'AMB || VACATION (2/15 - 2/19)'),
  ((select id from residents where sched_key='Lutz, G'),10,'CCU'),
  ((select id from residents where sched_key='Lutz, G'),11,'MED A'),
  ((select id from residents where sched_key='Lutz, G'),12,'IM CONS || VACATION (5/10 - 5/14)'),
  ((select id from residents where sched_key='Lutz, G'),13,'MED A'),
  ((select id from residents where sched_key='McInnis, M'),1,'ID CONSULT (7/1 - 7/12) || NF (7/13 - 7/26)'),
  ((select id from residents where sched_key='McInnis, M'),2,'CV CONSULTS'),
  ((select id from residents where sched_key='McInnis, M'),3,'MED C'),
  ((select id from residents where sched_key='McInnis, M'),4,'MICU D'),
  ((select id from residents where sched_key='McInnis, M'),5,'GENERAL NEURO || VACATION (10/26 - 10/30)'),
  ((select id from residents where sched_key='McInnis, M'),6,'MED A'),
  ((select id from residents where sched_key='McInnis, M'),7,'CCU'),
  ((select id from residents where sched_key='McInnis, M'),8,'ED MED || VACATION (2/1 - 2/5)'),
  ((select id from residents where sched_key='McInnis, M'),9,'MICU D'),
  ((select id from residents where sched_key='McInnis, M'),10,'MED B'),
  ((select id from residents where sched_key='McInnis, M'),11,'AMB'),
  ((select id from residents where sched_key='McInnis, M'),12,'MED D (5/3 - 5/16) || GI CONSULT (5/17 - 5/30)'),
  ((select id from residents where sched_key='McInnis, M'),13,'IM CONS || VACATION (6/21 - 6/25)'),
  ((select id from residents where sched_key='Modi, R'),1,'CCU'),
  ((select id from residents where sched_key='Modi, R'),2,'AMB'),
  ((select id from residents where sched_key='Modi, R'),3,'MED D'),
  ((select id from residents where sched_key='Modi, R'),4,'MICU C'),
  ((select id from residents where sched_key='Modi, R'),5,'IM CONS || VACATION (11/9 - 11/13)'),
  ((select id from residents where sched_key='Modi, R'),6,'GI CONSULT'),
  ((select id from residents where sched_key='Modi, R'),7,'GENERAL NEURO'),
  ((select id from residents where sched_key='Modi, R'),8,'MED A'),
  ((select id from residents where sched_key='Modi, R'),9,'PULM CONSULT (2/8 - 2/21) || VACATION (2/15 - 2/19) || NF (2/22 - 3/7)'),
  ((select id from residents where sched_key='Modi, R'),10,'MED C'),
  ((select id from residents where sched_key='Modi, R'),11,'ED MED || VACATION (4/12 - 4/16)'),
  ((select id from residents where sched_key='Modi, R'),12,'MED C'),
  ((select id from residents where sched_key='Modi, R'),13,'MICU C'),
  ((select id from residents where sched_key='Morales, G'),1,'MED A'),
  ((select id from residents where sched_key='Morales, G'),2,'GENERAL NEURO'),
  ((select id from residents where sched_key='Morales, G'),3,'MICU D'),
  ((select id from residents where sched_key='Morales, G'),4,'CV CONSULTS'),
  ((select id from residents where sched_key='Morales, G'),5,'MED D'),
  ((select id from residents where sched_key='Morales, G'),6,'NEPH CONS || VACATION (11/16 - 11/20)'),
  ((select id from residents where sched_key='Morales, G'),7,'MED C'),
  ((select id from residents where sched_key='Morales, G'),8,'MICU B'),
  ((select id from residents where sched_key='Morales, G'),9,'CCU'),
  ((select id from residents where sched_key='Morales, G'),10,'MED D'),
  ((select id from residents where sched_key='Morales, G'),11,'GI CONSULT || VACATION (4/12 - 4/16)'),
  ((select id from residents where sched_key='Morales, G'),12,'NF (5/3 - 5/16) || PULM CONSULT (5/17 - 5/30) || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Morales, G'),13,'CCU (5/31 - 6/13) || GENERAL NEURO (6/14 - 6/30)'),
  ((select id from residents where sched_key='Olberding, C'),1,'AMB'),
  ((select id from residents where sched_key='Olberding, C'),2,'NF (7/27 - 8/9) || GI CONSULT (8/10 - 8/23)'),
  ((select id from residents where sched_key='Olberding, C'),3,'MED E'),
  ((select id from residents where sched_key='Olberding, C'),4,'MED B'),
  ((select id from residents where sched_key='Olberding, C'),5,'GENERAL NEURO || VACATION (10/26 - 10/30)'),
  ((select id from residents where sched_key='Olberding, C'),6,'MICU D'),
  ((select id from residents where sched_key='Olberding, C'),7,'MED A'),
  ((select id from residents where sched_key='Olberding, C'),8,'IM CONS'),
  ((select id from residents where sched_key='Olberding, C'),9,'MED C'),
  ((select id from residents where sched_key='Olberding, C'),10,'ID CONSULT || VACATION (3/8 - 3/12)'),
  ((select id from residents where sched_key='Olberding, C'),11,'CCU'),
  ((select id from residents where sched_key='Olberding, C'),12,'ED MED || VACATION (5/10 - 5/14)'),
  ((select id from residents where sched_key='Olberding, C'),13,'MICU D'),
  ((select id from residents where sched_key='Patel, N'),1,'MICU D'),
  ((select id from residents where sched_key='Patel, N'),2,'MED D'),
  ((select id from residents where sched_key='Patel, N'),3,'IM CONS'),
  ((select id from residents where sched_key='Patel, N'),4,'NF (9/21 - 10/4) || ID CONSULT (10/5 - 10/18) || VACATION (10/12 - 10/16)'),
  ((select id from residents where sched_key='Patel, N'),5,'AMB'),
  ((select id from residents where sched_key='Patel, N'),6,'MED B'),
  ((select id from residents where sched_key='Patel, N'),7,'MED A'),
  ((select id from residents where sched_key='Patel, N'),8,'GI CONSULT'),
  ((select id from residents where sched_key='Patel, N'),9,'GENERAL NEURO || VACATION (2/15 - 2/19)'),
  ((select id from residents where sched_key='Patel, N'),10,'MICU C'),
  ((select id from residents where sched_key='Patel, N'),11,'CV CONSULTS'),
  ((select id from residents where sched_key='Patel, N'),12,'CCU'),
  ((select id from residents where sched_key='Patel, N'),13,'ED MED || VACATION (6/14 - 6/18)'),
  ((select id from residents where sched_key='Patel, S'),1,'NF (7/1 - 7/12) || NEPH CONS (7/13 - 7/26)'),
  ((select id from residents where sched_key='Patel, S'),2,'MICU C'),
  ((select id from residents where sched_key='Patel, S'),3,'MED D (8/24 - 9/6) || AMB (9/7 - 9/20)'),
  ((select id from residents where sched_key='Patel, S'),4,'GENERAL NEURO || VACATION (9/21 - 9/25)'),
  ((select id from residents where sched_key='Patel, S'),5,'CCU'),
  ((select id from residents where sched_key='Patel, S'),6,'AMB'),
  ((select id from residents where sched_key='Patel, S'),7,'IM CONS || VACATION (1/4 - 1/8)'),
  ((select id from residents where sched_key='Patel, S'),8,'MICU C'),
  ((select id from residents where sched_key='Patel, S'),9,'MED C'),
  ((select id from residents where sched_key='Patel, S'),10,'ED MED || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Patel, S'),11,'MED D'),
  ((select id from residents where sched_key='Patel, S'),12,'ID CONSULT (5/3 - 5/16) || MED D (5/17 - 5/30)'),
  ((select id from residents where sched_key='Patel, S'),13,'MED C'),
  ((select id from residents where sched_key='Perez, A'),1,'GI CONSULT'),
  ((select id from residents where sched_key='Perez, A'),2,'CCU'),
  ((select id from residents where sched_key='Perez, A'),3,'OPHTH-SHJ'),
  ((select id from residents where sched_key='Perez, A'),4,'MED A'),
  ((select id from residents where sched_key='Perez, A'),5,'MICU D'),
  ((select id from residents where sched_key='Perez, A'),6,'CV CONSULTS (11/16 - 11/29) || VACATION (11/23 - 11/27) || NF (11/30 - 12/13)'),
  ((select id from residents where sched_key='Perez, A'),7,'MED D'),
  ((select id from residents where sched_key='Perez, A'),8,'MICU D'),
  ((select id from residents where sched_key='Perez, A'),9,'GENERAL NEURO || VACATION (3/1 - 3/5)'),
  ((select id from residents where sched_key='Perez, A'),10,'OPHTH-SHJ'),
  ((select id from residents where sched_key='Perez, A'),11,'MED B'),
  ((select id from residents where sched_key='Perez, A'),12,'OPHTH-SHJ || VACATION (5/17 - 5/21)'),
  ((select id from residents where sched_key='Perez, A'),13,'MED C'),
  ((select id from residents where sched_key='Sasher, T'),1,'MED C'),
  ((select id from residents where sched_key='Sasher, T'),2,'NEPH CONS'),
  ((select id from residents where sched_key='Sasher, T'),3,'NF (8/24 - 9/6) || ID CONSULT (9/7 - 9/20)'),
  ((select id from residents where sched_key='Sasher, T'),4,'MED B'),
  ((select id from residents where sched_key='Sasher, T'),5,'OPHTH-SHJ || VACATION (10/26 - 10/30)'),
  ((select id from residents where sched_key='Sasher, T'),6,'GENERAL NEURO'),
  ((select id from residents where sched_key='Sasher, T'),7,'MED B'),
  ((select id from residents where sched_key='Sasher, T'),8,'CCU'),
  ((select id from residents where sched_key='Sasher, T'),9,'OPHTH-SHJ'),
  ((select id from residents where sched_key='Sasher, T'),10,'GI CONSULT (3/8 - 3/21) || VACATION (3/8 - 3/12) || NF (3/22 - 4/4)'),
  ((select id from residents where sched_key='Sasher, T'),11,'MICU D'),
  ((select id from residents where sched_key='Sasher, T'),12,'OPHTH-SHJ || VACATION (5/10 - 5/14)'),
  ((select id from residents where sched_key='Sasher, T'),13,'MED D'),
  ((select id from residents where sched_key='Todd, A'),1,'ED MED'),
  ((select id from residents where sched_key='Todd, A'),2,'AMB'),
  ((select id from residents where sched_key='Todd, A'),3,'MICU C'),
  ((select id from residents where sched_key='Todd, A'),4,'GENERAL NEURO || VACATION (9/28 - 10/2)'),
  ((select id from residents where sched_key='Todd, A'),5,'MED A'),
  ((select id from residents where sched_key='Todd, A'),6,'MED D'),
  ((select id from residents where sched_key='Todd, A'),7,'GI CONSULT'),
  ((select id from residents where sched_key='Todd, A'),8,'MED D'),
  ((select id from residents where sched_key='Todd, A'),9,'NF (2/8 - 2/21) || ID CONSULT (2/22 - 3/7) || VACATION (2/22 - 2/26)'),
  ((select id from residents where sched_key='Todd, A'),10,'MICU D'),
  ((select id from residents where sched_key='Todd, A'),11,'IM CONS || VACATION (4/12 - 4/16)'),
  ((select id from residents where sched_key='Todd, A'),12,'CCU'),
  ((select id from residents where sched_key='Todd, A'),13,'MED D'),
  ((select id from residents where sched_key='Wirth, T'),1,'IM CONS'),
  ((select id from residents where sched_key='Wirth, T'),2,'MICU D'),
  ((select id from residents where sched_key='Wirth, T'),3,'ED MED || VACATION (9/7 - 9/11)'),
  ((select id from residents where sched_key='Wirth, T'),4,'MED E'),
  ((select id from residents where sched_key='Wirth, T'),5,'MED B'),
  ((select id from residents where sched_key='Wirth, T'),6,'AMB'),
  ((select id from residents where sched_key='Wirth, T'),7,'CCU'),
  ((select id from residents where sched_key='Wirth, T'),8,'GENERAL NEURO'),
  ((select id from residents where sched_key='Wirth, T'),9,'MED D'),
  ((select id from residents where sched_key='Wirth, T'),10,'AMB (3/8 - 3/21) || ONC CONSULT (3/22 - 4/4) || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Wirth, T'),11,'MED B'),
  ((select id from residents where sched_key='Wirth, T'),12,'MED D'),
  ((select id from residents where sched_key='Wirth, T'),13,'NF (5/31 - 6/13) || GI CONSULT (6/14 - 6/30) || VACATION (6/14 - 6/18)'),
  ((select id from residents where sched_key='Casarcia, N'),1,'MED B'),
  ((select id from residents where sched_key='Casarcia, N'),2,'PULM CONSULT'),
  ((select id from residents where sched_key='Casarcia, N'),3,'CV CONSULTS'),
  ((select id from residents where sched_key='Casarcia, N'),4,'CCU'),
  ((select id from residents where sched_key='Casarcia, N'),5,'MED C'),
  ((select id from residents where sched_key='Casarcia, N'),6,'AMB (11/16 - 11/29) || NEPH CONS (11/30 - 12/13) || VACATION (11/30 - 12/4)'),
  ((select id from residents where sched_key='Casarcia, N'),7,'NF (12/14 - 12/27) || RHEUM CONSULTS (12/28 - 1/10)'),
  ((select id from residents where sched_key='Casarcia, N'),8,'CV CONSULTS'),
  ((select id from residents where sched_key='Casarcia, N'),9,'MICU B'),
  ((select id from residents where sched_key='Casarcia, N'),10,'RES-SHJ (3/8 - 3/21) || VACATION (3/15 - 3/19) || ENDO CONSULTS-UFSC (3/22 - 4/4)'),
  ((select id from residents where sched_key='Casarcia, N'),11,'GI CONSULT (4/5 - 4/18) || MED A (4/19 - 5/2)'),
  ((select id from residents where sched_key='Casarcia, N'),12,'ID CONSULT (5/3 - 5/16) || PS_QI (5/17 - 5/30) || VACATION (5/17 - 5/21)'),
  ((select id from residents where sched_key='Casarcia, N'),13,'NF (5/31 - 6/13) || AMB (6/14 - 6/30)'),
  ((select id from residents where sched_key='Clark, B'),1,'MED D'),
  ((select id from residents where sched_key='Clark, B'),2,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Clark, B'),3,'RES-SHJ (8/24 - 9/6) || NF (9/7 - 9/20)'),
  ((select id from residents where sched_key='Clark, B'),4,'NEPH CONS (9/21 - 10/4) || UF DERM DP (10/5 - 10/18)'),
  ((select id from residents where sched_key='Clark, B'),5,'ONC CONSULT'),
  ((select id from residents where sched_key='Clark, B'),6,'NEPH CONS (11/16 - 11/29) || VACATION (11/23 - 11/27) || NF (11/30 - 12/13)'),
  ((select id from residents where sched_key='Clark, B'),7,'CV CONSULTS'),
  ((select id from residents where sched_key='Clark, B'),8,'AMB || VACATION (2/1 - 2/5)'),
  ((select id from residents where sched_key='Clark, B'),9,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Clark, B'),10,'MICU C'),
  ((select id from residents where sched_key='Clark, B'),11,'MED B'),
  ((select id from residents where sched_key='Clark, B'),12,'PS_QI (5/3 - 5/16) || VACATION (5/3 - 5/7) || PULM CONSULT (5/17 - 5/30)'),
  ((select id from residents where sched_key='Clark, B'),13,'CCU'),
  ((select id from residents where sched_key='Collins, G'),1,'GI CONSULT'),
  ((select id from residents where sched_key='Collins, G'),2,'MED B'),
  ((select id from residents where sched_key='Collins, G'),3,'NEPH CONS'),
  ((select id from residents where sched_key='Collins, G'),4,'RES-SHJ (9/21 - 10/4) || VACATION (9/21 - 9/25) || NF (10/5 - 10/18)'),
  ((select id from residents where sched_key='Collins, G'),5,'PS_QI (10/19 - 11/1) || ONC CONSULT (11/2 - 11/15)'),
  ((select id from residents where sched_key='Collins, G'),6,'MICU C'),
  ((select id from residents where sched_key='Collins, G'),7,'CV CONSULTS'),
  ((select id from residents where sched_key='Collins, G'),8,'CCU'),
  ((select id from residents where sched_key='Collins, G'),9,'ID CONSULT || VACATION (3/1 - 3/5)'),
  ((select id from residents where sched_key='Collins, G'),10,'MED D (3/8 - 3/21) || PULM CONSULT (3/22 - 4/4)'),
  ((select id from residents where sched_key='Collins, G'),11,'AMB'),
  ((select id from residents where sched_key='Collins, G'),12,'NF (5/3 - 5/16) || GI CONSULT (5/17 - 5/30) || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Collins, G'),13,'MED D'),
  ((select id from residents where sched_key='Daniel, R'),1,'CCU'),
  ((select id from residents where sched_key='Daniel, R'),2,'GI CONSULT'),
  ((select id from residents where sched_key='Daniel, R'),3,'PS_QI (8/24 - 9/6) || ID CONSULT (9/7 - 9/20)'),
  ((select id from residents where sched_key='Daniel, R'),4,'NF (9/21 - 10/4) || RES-SHJ (10/5 - 10/18)'),
  ((select id from residents where sched_key='Daniel, R'),5,'MED B (10/19 - 11/1) || CV CONSULTS (11/2 - 11/15) || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Daniel, R'),6,'AMB'),
  ((select id from residents where sched_key='Daniel, R'),7,'PULM CONSULT'),
  ((select id from residents where sched_key='Daniel, R'),8,'MICU B (1/11 - 1/24) || NEPH CONS (1/25 - 2/7)'),
  ((select id from residents where sched_key='Daniel, R'),9,'MED A'),
  ((select id from residents where sched_key='Daniel, R'),10,'ONC CONSULT || VACATION (3/15 - 3/19)'),
  ((select id from residents where sched_key='Daniel, R'),11,'MICU C'),
  ((select id from residents where sched_key='Daniel, R'),12,'CV CONSULTS (5/3 - 5/16) || RHEUM CONSULTS (5/17 - 5/30)'),
  ((select id from residents where sched_key='Daniel, R'),13,'CV CONSULTS (5/31 - 6/13) || VACATION (6/7 - 6/11) || NF (6/14 - 6/30)'),
  ((select id from residents where sched_key='Dyer, N'),1,'NEPH CONS || VACATION (7/6 - 7/10)'),
  ((select id from residents where sched_key='Dyer, N'),2,'ID CONSULT (7/27 - 8/9) || ONC CONSULT (8/10 - 8/23)'),
  ((select id from residents where sched_key='Dyer, N'),3,'MED E'),
  ((select id from residents where sched_key='Dyer, N'),4,'GI CONSULT || VACATION (10/5 - 10/9)'),
  ((select id from residents where sched_key='Dyer, N'),5,'MICU B'),
  ((select id from residents where sched_key='Dyer, N'),6,'NF (11/16 - 11/29) || PULM CONSULT (11/30 - 12/13)'),
  ((select id from residents where sched_key='Dyer, N'),7,'AMB (12/14 - 12/27) || CV CONSULTS (12/28 - 1/10)'),
  ((select id from residents where sched_key='Dyer, N'),8,'ID CONSULT || VACATION (1/18 - 1/22)'),
  ((select id from residents where sched_key='Dyer, N'),9,'CCU'),
  ((select id from residents where sched_key='Dyer, N'),10,'MED B'),
  ((select id from residents where sched_key='Dyer, N'),11,'RES-SHJ (4/5 - 4/18) || NF (4/19 - 5/2)'),
  ((select id from residents where sched_key='Dyer, N'),12,'RHEUM CONSULTS (5/3 - 5/16) || PS_QI (5/17 - 5/30)'),
  ((select id from residents where sched_key='Dyer, N'),13,'MICU B'),
  ((select id from residents where sched_key='Gandhi, S'),1,'CV CONSULTS || VACATION (7/13 - 7/17)'),
  ((select id from residents where sched_key='Gandhi, S'),2,'MED A'),
  ((select id from residents where sched_key='Gandhi, S'),3,'CCU'),
  ((select id from residents where sched_key='Gandhi, S'),4,'AMB'),
  ((select id from residents where sched_key='Gandhi, S'),5,'RHEUM CONSULTS (10/19 - 11/1) || NF (11/2 - 11/15)'),
  ((select id from residents where sched_key='Gandhi, S'),6,'PULM CONSULT || VACATION (11/16 - 11/20)'),
  ((select id from residents where sched_key='Gandhi, S'),7,'MED C'),
  ((select id from residents where sched_key='Gandhi, S'),8,'RES-SHJ (1/11 - 1/24) || ENDO CONSULTS-UFSC (1/25 - 2/7)'),
  ((select id from residents where sched_key='Gandhi, S'),9,'MICU C'),
  ((select id from residents where sched_key='Gandhi, S'),10,'ID CONSULT || VACATION (3/29 - 4/2)'),
  ((select id from residents where sched_key='Gandhi, S'),11,'NEPH CONS'),
  ((select id from residents where sched_key='Gandhi, S'),12,'MED B (5/3 - 5/16) || PS_QI (5/17 - 5/30)'),
  ((select id from residents where sched_key='Gandhi, S'),13,'NF (5/31 - 6/13) || AMB (6/14 - 6/30)'),
  ((select id from residents where sched_key='Hicks, S'),1,'NF (7/1 - 7/12) || ONC CONSULT (7/13 - 7/26) || VACATION (7/20 - 7/24)'),
  ((select id from residents where sched_key='Hicks, S'),2,'NEPH CONS'),
  ((select id from residents where sched_key='Hicks, S'),3,'MED D'),
  ((select id from residents where sched_key='Hicks, S'),4,'CCU'),
  ((select id from residents where sched_key='Hicks, S'),5,'PS_QI (10/19 - 11/1) || RES-SHJ (11/2 - 11/15) || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Hicks, S'),6,'MED D'),
  ((select id from residents where sched_key='Hicks, S'),7,'AMB'),
  ((select id from residents where sched_key='Hicks, S'),8,'CV CONSULTS'),
  ((select id from residents where sched_key='Hicks, S'),9,'MICU D (2/8 - 2/21) || ID CONSULT (2/22 - 3/7)'),
  ((select id from residents where sched_key='Hicks, S'),10,'RHEUM CONSULTS || VACATION (3/29 - 4/2)'),
  ((select id from residents where sched_key='Hicks, S'),11,'PULM CONSULT'),
  ((select id from residents where sched_key='Hicks, S'),12,'MICU C'),
  ((select id from residents where sched_key='Hicks, S'),13,'GI CONSULT (5/31 - 6/13) || NF (6/14 - 6/30)'),
  ((select id from residents where sched_key='Kiri, G'),1,'AMB'),
  ((select id from residents where sched_key='Kiri, G'),2,'MED B'),
  ((select id from residents where sched_key='Kiri, G'),3,'PS_QI (8/24 - 9/6) || VACATION (8/24 - 8/28) || ONC CONSULT (9/7 - 9/20)'),
  ((select id from residents where sched_key='Kiri, G'),4,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Kiri, G'),5,'NF (10/19 - 11/1) || PULM CONSULT (11/2 - 11/15)'),
  ((select id from residents where sched_key='Kiri, G'),6,'ID CONSULT || VACATION (11/16 - 11/20)'),
  ((select id from residents where sched_key='Kiri, G'),7,'MICU C'),
  ((select id from residents where sched_key='Kiri, G'),8,'NEPH CONS (1/11 - 1/24) || NF (1/25 - 2/7)'),
  ((select id from residents where sched_key='Kiri, G'),9,'MED B'),
  ((select id from residents where sched_key='Kiri, G'),10,'ONC CONSULT (3/8 - 3/21) || MED A (3/22 - 4/4)'),
  ((select id from residents where sched_key='Kiri, G'),11,'PULM CONSULT || VACATION (4/19 - 4/23)'),
  ((select id from residents where sched_key='Kiri, G'),12,'MICU B'),
  ((select id from residents where sched_key='Kiri, G'),13,'CV CONSULTS'),
  ((select id from residents where sched_key='Kumar, R'),1,'NEPH CONS'),
  ((select id from residents where sched_key='Kumar, R'),2,'MED D'),
  ((select id from residents where sched_key='Kumar, R'),3,'NF (8/24 - 9/6) || RES-SHJ (9/7 - 9/20)'),
  ((select id from residents where sched_key='Kumar, R'),4,'MED E'),
  ((select id from residents where sched_key='Kumar, R'),5,'GI CONSULT'),
  ((select id from residents where sched_key='Kumar, R'),6,'AMB || VACATION (11/16 - 11/20)'),
  ((select id from residents where sched_key='Kumar, R'),7,'MICU D'),
  ((select id from residents where sched_key='Kumar, R'),8,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Kumar, R'),9,'ENDO CONSULTS-UFSC (2/8 - 2/21) || PS_QI (2/22 - 3/7) || VACATION (3/1 - 3/5)'),
  ((select id from residents where sched_key='Kumar, R'),10,'PULM CONSULT'),
  ((select id from residents where sched_key='Kumar, R'),11,'CCU'),
  ((select id from residents where sched_key='Kumar, R'),12,'ONC CONSULT || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Kumar, R'),13,'MICU D'),
  ((select id from residents where sched_key='Mason, D'),1,'MED A'),
  ((select id from residents where sched_key='Mason, D'),2,'NF (7/27 - 8/9) || UF DERM DP (8/10 - 8/23)'),
  ((select id from residents where sched_key='Mason, D'),3,'CV CONSULTS'),
  ((select id from residents where sched_key='Mason, D'),4,'NEPH CONS || VACATION (10/5 - 10/9)'),
  ((select id from residents where sched_key='Mason, D'),5,'MICU C'),
  ((select id from residents where sched_key='Mason, D'),6,'ENDO CONSULTS-UFSC (11/16 - 11/29) || RES-SHJ (11/30 - 12/13)'),
  ((select id from residents where sched_key='Mason, D'),7,'MED D'),
  ((select id from residents where sched_key='Mason, D'),8,'PULM CONSULT'),
  ((select id from residents where sched_key='Mason, D'),9,'ONC CONSULT (2/8 - 2/21) || VACATION (2/8 - 2/12) || PS_QI (2/22 - 3/7)'),
  ((select id from residents where sched_key='Mason, D'),10,'CCU'),
  ((select id from residents where sched_key='Mason, D'),11,'RHEUM CONSULTS || VACATION (4/26 - 4/30)'),
  ((select id from residents where sched_key='Mason, D'),12,'MED D'),
  ((select id from residents where sched_key='Mason, D'),13,'MICU C'),
  ((select id from residents where sched_key='Osherov, L'),1,'MED C'),
  ((select id from residents where sched_key='Osherov, L'),2,'CV CONSULTS'),
  ((select id from residents where sched_key='Osherov, L'),3,'ONC CONSULT (8/24 - 9/6) || PS_QI (9/7 - 9/20)'),
  ((select id from residents where sched_key='Osherov, L'),4,'ID CONSULT || VACATION (9/21 - 9/25)'),
  ((select id from residents where sched_key='Osherov, L'),5,'CCU'),
  ((select id from residents where sched_key='Osherov, L'),6,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Osherov, L'),7,'NEPH CONS || VACATION (1/4 - 1/8)'),
  ((select id from residents where sched_key='Osherov, L'),8,'MICU D'),
  ((select id from residents where sched_key='Osherov, L'),9,'AMB'),
  ((select id from residents where sched_key='Osherov, L'),10,'RES-SHJ (3/8 - 3/21) || NF (3/22 - 4/4)'),
  ((select id from residents where sched_key='Osherov, L'),11,'ONC CONSULT || VACATION (4/5 - 4/9)'),
  ((select id from residents where sched_key='Osherov, L'),12,'CCU'),
  ((select id from residents where sched_key='Osherov, L'),13,'MED A'),
  ((select id from residents where sched_key='Pierce, E'),1,'ID CONSULT'),
  ((select id from residents where sched_key='Pierce, E'),2,'MED C'),
  ((select id from residents where sched_key='Pierce, E'),3,'PULM CONSULT'),
  ((select id from residents where sched_key='Pierce, E'),4,'MICU D'),
  ((select id from residents where sched_key='Pierce, E'),5,'CV CONSULTS || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Pierce, E'),6,'CCU'),
  ((select id from residents where sched_key='Pierce, E'),7,'ONC CONSULT'),
  ((select id from residents where sched_key='Pierce, E'),8,'NF (1/11 - 1/24) || RES-SHJ (1/25 - 2/7)'),
  ((select id from residents where sched_key='Pierce, E'),9,'NEPH CONS (2/8 - 2/21) || PS_QI (2/22 - 3/7) || VACATION (2/22 - 2/26)'),
  ((select id from residents where sched_key='Pierce, E'),10,'AMB'),
  ((select id from residents where sched_key='Pierce, E'),11,'MICU B'),
  ((select id from residents where sched_key='Pierce, E'),12,'ENDO CONSULTS-UFSC || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Pierce, E'),13,'MED C'),
  ((select id from residents where sched_key='Stiglich, A'),1,'MED B'),
  ((select id from residents where sched_key='Stiglich, A'),2,'PULM CONSULT || VACATION (8/3 - 8/7)'),
  ((select id from residents where sched_key='Stiglich, A'),3,'PS_QI (8/24 - 9/6) || RHEUM CONSULTS (9/7 - 9/20)'),
  ((select id from residents where sched_key='Stiglich, A'),4,'ID CONSULT'),
  ((select id from residents where sched_key='Stiglich, A'),5,'ENDO CONSULTS-UFSC || VACATION (11/9 - 11/13)'),
  ((select id from residents where sched_key='Stiglich, A'),6,'MICU B'),
  ((select id from residents where sched_key='Stiglich, A'),7,'GI CONSULT (12/14 - 12/27) || NF (12/28 - 1/10)'),
  ((select id from residents where sched_key='Stiglich, A'),8,'MED B'),
  ((select id from residents where sched_key='Stiglich, A'),9,'AMB'),
  ((select id from residents where sched_key='Stiglich, A'),10,'NF (3/8 - 3/21) || RES-SHJ (3/22 - 4/4) || VACATION (3/29 - 4/2)'),
  ((select id from residents where sched_key='Stiglich, A'),11,'CV CONSULTS'),
  ((select id from residents where sched_key='Stiglich, A'),12,'MICU D'),
  ((select id from residents where sched_key='Stiglich, A'),13,'NEPH CONS'),
  ((select id from residents where sched_key='Theriault, J'),1,'AMB (7/1 - 7/12) || NF (7/13 - 7/26)'),
  ((select id from residents where sched_key='Theriault, J'),2,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Theriault, J'),3,'MED B'),
  ((select id from residents where sched_key='Theriault, J'),4,'RES-SHJ (9/21 - 10/4) || NEPH CONS (10/5 - 10/18)'),
  ((select id from residents where sched_key='Theriault, J'),5,'CV CONSULTS || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Theriault, J'),6,'CCU'),
  ((select id from residents where sched_key='Theriault, J'),7,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Theriault, J'),8,'MED A'),
  ((select id from residents where sched_key='Theriault, J'),9,'AMB (2/8 - 2/21) || PS_QI (2/22 - 3/7) || VACATION (3/1 - 3/5)'),
  ((select id from residents where sched_key='Theriault, J'),10,'MICU D'),
  ((select id from residents where sched_key='Theriault, J'),11,'ENDO CONSULTS-UFSC (4/5 - 4/18) || MED C (4/19 - 5/2)'),
  ((select id from residents where sched_key='Theriault, J'),12,'ID CONSULT (5/3 - 5/16) || VACATION (5/3 - 5/7) || NF (5/17 - 5/30)'),
  ((select id from residents where sched_key='Theriault, J'),13,'CCU'),
  ((select id from residents where sched_key='Wilson, B'),1,'MED A'),
  ((select id from residents where sched_key='Wilson, B'),2,'ONC CONSULT (7/27 - 8/9) || NF (8/10 - 8/23)'),
  ((select id from residents where sched_key='Wilson, B'),3,'RHEUM CONSULTS (8/24 - 9/6) || PS_QI (9/7 - 9/20)'),
  ((select id from residents where sched_key='Wilson, B'),4,'PULM CONSULT || VACATION (9/21 - 9/25)'),
  ((select id from residents where sched_key='Wilson, B'),5,'MICU B'),
  ((select id from residents where sched_key='Wilson, B'),6,'CV CONSULTS'),
  ((select id from residents where sched_key='Wilson, B'),7,'AMB'),
  ((select id from residents where sched_key='Wilson, B'),8,'MED C'),
  ((select id from residents where sched_key='Wilson, B'),9,'RES-SHJ (2/8 - 2/21) || NF (2/22 - 3/7)'),
  ((select id from residents where sched_key='Wilson, B'),10,'NEPH CONS || VACATION (3/15 - 3/19)'),
  ((select id from residents where sched_key='Wilson, B'),11,'MICU D'),
  ((select id from residents where sched_key='Wilson, B'),12,'GI CONSULT || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Wilson, B'),13,'MED B'),
  ((select id from residents where sched_key='Woodbeck, B'),1,'CV CONSULTS'),
  ((select id from residents where sched_key='Woodbeck, B'),2,'MED A'),
  ((select id from residents where sched_key='Woodbeck, B'),3,'NEPH CONS'),
  ((select id from residents where sched_key='Woodbeck, B'),4,'MED B'),
  ((select id from residents where sched_key='Woodbeck, B'),5,'PULM CONSULT (10/19 - 11/1) || RES-SHJ (11/2 - 11/15) || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Woodbeck, B'),6,'MICU D'),
  ((select id from residents where sched_key='Woodbeck, B'),7,'ID CONSULT'),
  ((select id from residents where sched_key='Woodbeck, B'),8,'GI CONSULT'),
  ((select id from residents where sched_key='Woodbeck, B'),9,'NF (2/8 - 2/21) || PS_QI (2/22 - 3/7) || VACATION (3/1 - 3/5)'),
  ((select id from residents where sched_key='Woodbeck, B'),10,'ONC CONSULT'),
  ((select id from residents where sched_key='Woodbeck, B'),11,'NF (4/5 - 4/18) || RHEUM CONSULTS (4/19 - 5/2) || VACATION (4/26 - 4/30)'),
  ((select id from residents where sched_key='Woodbeck, B'),12,'CCU'),
  ((select id from residents where sched_key='Woodbeck, B'),13,'AMB (5/31 - 6/13) || IM CONS (6/14 - 6/30)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),1,'MED D'),
  ((select id from residents where sched_key='Aleman Oliva, C'),2,'NEPH CONS || VACATION (8/10 - 8/14)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),3,'AMB'),
  ((select id from residents where sched_key='Aleman Oliva, C'),4,'PULM CONSULT (9/21 - 10/4) || NF (10/5 - 10/18)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),5,'PALLIATIVE'),
  ((select id from residents where sched_key='Aleman Oliva, C'),6,'ENDO CONSULTS-UFSC (11/16 - 11/29) || UF DERM DP (11/30 - 12/13) || VACATION (11/30 - 12/4)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),7,'IM CONS'),
  ((select id from residents where sched_key='Aleman Oliva, C'),8,'CCU'),
  ((select id from residents where sched_key='Aleman Oliva, C'),9,'RHEUM CONSULTS (2/8 - 2/21) || MED C (2/22 - 3/7)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),10,'AMB || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),11,'ONC CONSULT (4/5 - 4/18) || NF (4/19 - 5/2)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),12,'AMB (5/3 - 5/16) || ID CONSULT (5/17 - 5/30)'),
  ((select id from residents where sched_key='Aleman Oliva, C'),13,'CV CONSULTS'),
  ((select id from residents where sched_key='Choudhry, H'),1,'ENDO CONSULTS-UFSC (7/1 - 7/12) || AMB (7/13 - 7/26)'),
  ((select id from residents where sched_key='Choudhry, H'),2,'MICU C'),
  ((select id from residents where sched_key='Choudhry, H'),3,'MED A'),
  ((select id from residents where sched_key='Choudhry, H'),4,'AMB'),
  ((select id from residents where sched_key='Choudhry, H'),5,'CCU'),
  ((select id from residents where sched_key='Choudhry, H'),6,'ONC CONSULT || VACATION (11/30 - 12/4)'),
  ((select id from residents where sched_key='Choudhry, H'),7,'NF (12/14 - 12/27) || AMB (12/28 - 1/10)'),
  ((select id from residents where sched_key='Choudhry, H'),8,'RHEUM CONSULTS (1/11 - 1/24) || MICU C (1/25 - 2/7)'),
  ((select id from residents where sched_key='Choudhry, H'),9,'PALLIATIVE'),
  ((select id from residents where sched_key='Choudhry, H'),10,'PULM CONSULT (3/8 - 3/21) || VACATION (3/8 - 3/12) || ENDO CONSULTS-UFSC (3/22 - 4/4)'),
  ((select id from residents where sched_key='Choudhry, H'),11,'UF DERM DP (4/5 - 4/18) || IM CONS (4/19 - 5/2)'),
  ((select id from residents where sched_key='Choudhry, H'),12,'NEPH CONS (5/3 - 5/16) || CV CONSULTS (5/17 - 5/30) || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Choudhry, H'),13,'GI CONSULT'),
  ((select id from residents where sched_key='Chrystman, A'),1,'MICU A'),
  ((select id from residents where sched_key='Chrystman, A'),2,'IM CONS || VACATION (8/10 - 8/14)'),
  ((select id from residents where sched_key='Chrystman, A'),3,'MED C'),
  ((select id from residents where sched_key='Chrystman, A'),4,'ONC CONSULT'),
  ((select id from residents where sched_key='Chrystman, A'),5,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Chrystman, A'),6,'PALLIATIVE || VACATION (11/30 - 12/4)'),
  ((select id from residents where sched_key='Chrystman, A'),7,'PULM CONSULT (12/14 - 12/27) || AMB (12/28 - 1/10)'),
  ((select id from residents where sched_key='Chrystman, A'),8,'AMB'),
  ((select id from residents where sched_key='Chrystman, A'),9,'MED D'),
  ((select id from residents where sched_key='Chrystman, A'),10,'CCU'),
  ((select id from residents where sched_key='Chrystman, A'),11,'ID CONSULT (4/5 - 4/18) || GI CONSULT (4/19 - 5/2) || VACATION (4/26 - 4/30)'),
  ((select id from residents where sched_key='Chrystman, A'),12,'UF DERM DP (5/3 - 5/16) || NF (5/17 - 5/30)'),
  ((select id from residents where sched_key='Chrystman, A'),13,'NEPH CONS'),
  ((select id from residents where sched_key='den Boef, A'),1,'IM CONS'),
  ((select id from residents where sched_key='den Boef, A'),2,'MICU B'),
  ((select id from residents where sched_key='den Boef, A'),3,'AMB (8/24 - 9/6) || ONC CONSULT (9/7 - 9/20)'),
  ((select id from residents where sched_key='den Boef, A'),4,'PULM CONSULT'),
  ((select id from residents where sched_key='den Boef, A'),5,'ID CONSULT (10/19 - 11/1) || NF (11/2 - 11/15)'),
  ((select id from residents where sched_key='den Boef, A'),6,'CV CONSULTS (11/16 - 11/29) || VACATION (11/16 - 11/20) || MED A (11/30 - 12/13)'),
  ((select id from residents where sched_key='den Boef, A'),7,'NEPH CONS'),
  ((select id from residents where sched_key='den Boef, A'),8,'GI CONSULT'),
  ((select id from residents where sched_key='den Boef, A'),9,'UF DERM DP (2/8 - 2/21) || VACATION (2/15 - 2/19) || MICU D (2/22 - 3/7)'),
  ((select id from residents where sched_key='den Boef, A'),10,'AMB (3/8 - 3/21) || NF (3/22 - 4/4)'),
  ((select id from residents where sched_key='den Boef, A'),11,'PALLIATIVE'),
  ((select id from residents where sched_key='den Boef, A'),12,'CV CONSULTS (5/3 - 5/16) || VACATION (5/3 - 5/7) || MED B (5/17 - 5/30)'),
  ((select id from residents where sched_key='den Boef, A'),13,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Desai, P'),1,'PALLIATIVE'),
  ((select id from residents where sched_key='Desai, P'),2,'MED C'),
  ((select id from residents where sched_key='Desai, P'),3,'ID CONSULT (8/24 - 9/6) || IM CONS (9/7 - 9/20)'),
  ((select id from residents where sched_key='Desai, P'),4,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Desai, P'),5,'NF (10/19 - 11/1) || NEPH CONS (11/2 - 11/15)'),
  ((select id from residents where sched_key='Desai, P'),6,'UF DERM DP (11/16 - 11/29) || VACATION (11/16 - 11/20) || CV CONSULTS (11/30 - 12/13)'),
  ((select id from residents where sched_key='Desai, P'),7,'MICU B'),
  ((select id from residents where sched_key='Desai, P'),8,'ONC CONSULT || VACATION (1/18 - 1/22)'),
  ((select id from residents where sched_key='Desai, P'),9,'MED C (2/8 - 2/21) || ENDO CONSULTS-UFSC (2/22 - 3/7)'),
  ((select id from residents where sched_key='Desai, P'),10,'CV CONSULTS || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Desai, P'),11,'CCU'),
  ((select id from residents where sched_key='Desai, P'),12,'AMB'),
  ((select id from residents where sched_key='Desai, P'),13,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Gaudin, J'),1,'MICU B'),
  ((select id from residents where sched_key='Gaudin, J'),2,'PALLIATIVE'),
  ((select id from residents where sched_key='Gaudin, J'),3,'ID CONSULT (8/24 - 9/6) || NF (9/7 - 9/20)'),
  ((select id from residents where sched_key='Gaudin, J'),4,'AMB (9/21 - 10/4) || RHEUM CONSULTS (10/5 - 10/18) || VACATION (10/12 - 10/16)'),
  ((select id from residents where sched_key='Gaudin, J'),5,'MED A'),
  ((select id from residents where sched_key='Gaudin, J'),6,'IM CONS'),
  ((select id from residents where sched_key='Gaudin, J'),7,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Gaudin, J'),8,'NF (1/11 - 1/24) || AMB (1/25 - 2/7) || VACATION (2/1 - 2/5)'),
  ((select id from residents where sched_key='Gaudin, J'),9,'PULM CONSULT'),
  ((select id from residents where sched_key='Gaudin, J'),10,'CV CONSULTS || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Gaudin, J'),11,'AMB'),
  ((select id from residents where sched_key='Gaudin, J'),12,'UF DERM DP (5/3 - 5/16) || NEPH CONS (5/17 - 5/30)'),
  ((select id from residents where sched_key='Gaudin, J'),13,'GI CONSULT'),
  ((select id from residents where sched_key='Haley, A'),1,'ONC CONSULT (7/1 - 7/12) || NF (7/13 - 7/26)'),
  ((select id from residents where sched_key='Haley, A'),2,'MICU D'),
  ((select id from residents where sched_key='Haley, A'),3,'PALLIATIVE || VACATION (8/24 - 8/28)'),
  ((select id from residents where sched_key='Haley, A'),4,'NF (9/21 - 10/4) || AMB (10/5 - 10/18)'),
  ((select id from residents where sched_key='Haley, A'),5,'PULM CONSULT'),
  ((select id from residents where sched_key='Haley, A'),6,'GI CONSULT || VACATION (11/16 - 11/20)'),
  ((select id from residents where sched_key='Haley, A'),7,'ID CONSULT (12/14 - 12/27) || RHEUM CONSULTS (12/28 - 1/10)'),
  ((select id from residents where sched_key='Haley, A'),8,'MICU C (1/11 - 1/24) || GI CONSULT (1/25 - 2/7)'),
  ((select id from residents where sched_key='Haley, A'),9,'CV CONSULTS'),
  ((select id from residents where sched_key='Haley, A'),10,'MED C'),
  ((select id from residents where sched_key='Haley, A'),11,'AMB (4/5 - 4/18) || ENDO CONSULTS-UFSC (4/19 - 5/2) || VACATION (4/19 - 4/23)'),
  ((select id from residents where sched_key='Haley, A'),12,'NEPH CONS'),
  ((select id from residents where sched_key='Haley, A'),13,'IM CONS'),
  ((select id from residents where sched_key='Heathcoat, N'),1,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Heathcoat, N'),2,'AMB'),
  ((select id from residents where sched_key='Heathcoat, N'),3,'MICU C'),
  ((select id from residents where sched_key='Heathcoat, N'),4,'MED C'),
  ((select id from residents where sched_key='Heathcoat, N'),5,'ID CONSULT (10/19 - 11/1) || VACATION (10/26 - 10/30) || MED B (11/2 - 11/15)'),
  ((select id from residents where sched_key='Heathcoat, N'),6,'PULM CONSULT (11/16 - 11/29) || NF (11/30 - 12/13)'),
  ((select id from residents where sched_key='Heathcoat, N'),7,'ONC CONSULT'),
  ((select id from residents where sched_key='Heathcoat, N'),8,'NEPH CONS (1/11 - 1/24) || MICU B (1/25 - 2/7)'),
  ((select id from residents where sched_key='Heathcoat, N'),9,'GI CONSULT'),
  ((select id from residents where sched_key='Heathcoat, N'),10,'MED A (3/8 - 3/21) || RHEUM CONSULTS (3/22 - 4/4) || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Heathcoat, N'),11,'IM CONS (4/5 - 4/18) || PALLIATIVE (4/19 - 5/2)'),
  ((select id from residents where sched_key='Heathcoat, N'),12,'PALLIATIVE (5/3 - 5/16) || ENDO CONSULTS-UFSC (5/17 - 5/30) || VACATION (5/17 - 5/21)'),
  ((select id from residents where sched_key='Heathcoat, N'),13,'UF DERM DP (5/31 - 6/13) || RHEUM CONSULTS (6/14 - 6/30)'),
  ((select id from residents where sched_key='Loyola, G'),1,'UF DERM DP (7/1 - 7/12) || ENDO CONSULTS-UFSC (7/13 - 7/26)'),
  ((select id from residents where sched_key='Loyola, G'),2,'CCU'),
  ((select id from residents where sched_key='Loyola, G'),3,'IM CONS'),
  ((select id from residents where sched_key='Loyola, G'),4,'ONC CONSULT (9/21 - 10/4) || CV CONSULTS (10/5 - 10/18)'),
  ((select id from residents where sched_key='Loyola, G'),5,'AMB'),
  ((select id from residents where sched_key='Loyola, G'),6,'NF (11/16 - 11/29) || AMB (11/30 - 12/13) || VACATION (12/7 - 12/11)'),
  ((select id from residents where sched_key='Loyola, G'),7,'MED A'),
  ((select id from residents where sched_key='Loyola, G'),8,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Loyola, G'),9,'PULM CONSULT (2/8 - 2/21) || NF (2/22 - 3/7)'),
  ((select id from residents where sched_key='Loyola, G'),10,'GI CONSULT || VACATION (3/8 - 3/12)'),
  ((select id from residents where sched_key='Loyola, G'),11,'MED C (4/5 - 4/18) || ENDO CONSULTS-UFSC (4/19 - 5/2)'),
  ((select id from residents where sched_key='Loyola, G'),12,'PALLIATIVE || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Loyola, G'),13,'ID CONSULT'),
  ((select id from residents where sched_key='Merry, T'),1,'NF (7/1 - 7/12) || UF DERM DP (7/13 - 7/26) || VACATION (7/20 - 7/24)'),
  ((select id from residents where sched_key='Merry, T'),2,'ENDO CONSULTS-UFSC (7/27 - 8/9) || CV CONSULTS (8/10 - 8/23)'),
  ((select id from residents where sched_key='Merry, T'),3,'MICU D'),
  ((select id from residents where sched_key='Merry, T'),4,'IM CONS'),
  ((select id from residents where sched_key='Merry, T'),5,'AMB'),
  ((select id from residents where sched_key='Merry, T'),6,'MED C'),
  ((select id from residents where sched_key='Merry, T'),7,'GI CONSULT || VACATION (1/4 - 1/8)'),
  ((select id from residents where sched_key='Merry, T'),8,'PALLIATIVE'),
  ((select id from residents where sched_key='Merry, T'),9,'NF (2/8 - 2/21) || PULM CONSULT (2/22 - 3/7)'),
  ((select id from residents where sched_key='Merry, T'),10,'ENDO CONSULTS-UFSC || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Merry, T'),11,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Merry, T'),12,'MED A'),
  ((select id from residents where sched_key='Merry, T'),13,'AMB (5/31 - 6/13) || ONC CONSULT (6/14 - 6/30)'),
  ((select id from residents where sched_key='Parekh, S'),1,'MICU C'),
  ((select id from residents where sched_key='Parekh, S'),2,'NF (7/27 - 8/9) || GI CONSULT (8/10 - 8/23)'),
  ((select id from residents where sched_key='Parekh, S'),3,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Parekh, S'),4,'PALLIATIVE'),
  ((select id from residents where sched_key='Parekh, S'),5,'NEPH CONS'),
  ((select id from residents where sched_key='Parekh, S'),6,'ID CONSULT || VACATION (11/16 - 11/20)'),
  ((select id from residents where sched_key='Parekh, S'),7,'CCU'),
  ((select id from residents where sched_key='Parekh, S'),8,'MED D'),
  ((select id from residents where sched_key='Parekh, S'),9,'AMB (2/8 - 2/21) || AMB (2/22 - 3/7)'),
  ((select id from residents where sched_key='Parekh, S'),10,'NF (3/8 - 3/21) || UF DERM DP (3/22 - 4/4) || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Parekh, S'),11,'ENDO CONSULTS-UFSC (4/5 - 4/18) || MED D (4/19 - 5/2)'),
  ((select id from residents where sched_key='Parekh, S'),12,'IM CONS || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Parekh, S'),13,'AMB'),
  ((select id from residents where sched_key='Petrasko, P'),1,'PULM CONSULT || VACATION (7/6 - 7/10)'),
  ((select id from residents where sched_key='Petrasko, P'),2,'CCU'),
  ((select id from residents where sched_key='Petrasko, P'),3,'CV CONSULTS || VACATION (8/31 - 9/4)'),
  ((select id from residents where sched_key='Petrasko, P'),4,'GI CONSULT'),
  ((select id from residents where sched_key='Petrasko, P'),5,'IM CONS (10/19 - 11/1) || UF DERM DP (11/2 - 11/15)'),
  ((select id from residents where sched_key='Petrasko, P'),6,'MED B'),
  ((select id from residents where sched_key='Petrasko, P'),7,'PALLIATIVE'),
  ((select id from residents where sched_key='Petrasko, P'),8,'AMB (1/11 - 1/24) || NF (1/25 - 2/7)'),
  ((select id from residents where sched_key='Petrasko, P'),9,'ONC CONSULT'),
  ((select id from residents where sched_key='Petrasko, P'),10,'AMB (3/8 - 3/21) || VACATION (3/8 - 3/12) || MED D (3/22 - 4/4)'),
  ((select id from residents where sched_key='Petrasko, P'),11,'MED D (4/5 - 4/18) || ID CONSULT (4/19 - 5/2)'),
  ((select id from residents where sched_key='Petrasko, P'),12,'MED C'),
  ((select id from residents where sched_key='Petrasko, P'),13,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Rahman, Z'),1,'MICU D'),
  ((select id from residents where sched_key='Rahman, Z'),2,'ONC CONSULT (7/27 - 8/9) || NF (8/10 - 8/23)'),
  ((select id from residents where sched_key='Rahman, Z'),3,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Rahman, Z'),4,'MED D'),
  ((select id from residents where sched_key='Rahman, Z'),5,'PALLIATIVE'),
  ((select id from residents where sched_key='Rahman, Z'),6,'MED A (11/16 - 11/29) || CV CONSULTS (11/30 - 12/13) || VACATION (11/30 - 12/4)'),
  ((select id from residents where sched_key='Rahman, Z'),7,'CCU'),
  ((select id from residents where sched_key='Rahman, Z'),8,'UF DERM DP (1/11 - 1/24) || ID CONSULT (1/25 - 2/7)'),
  ((select id from residents where sched_key='Rahman, Z'),9,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Rahman, Z'),10,'IM CONS || VACATION (3/8 - 3/12)'),
  ((select id from residents where sched_key='Rahman, Z'),11,'ID CONSULT'),
  ((select id from residents where sched_key='Rahman, Z'),12,'AMB || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Rahman, Z'),13,'ID CONSULT'),
  ((select id from residents where sched_key='Santharam, Y'),1,'PALLIATIVE'),
  ((select id from residents where sched_key='Santharam, Y'),2,'MED D'),
  ((select id from residents where sched_key='Santharam, Y'),3,'GI CONSULT (8/24 - 9/6) || UF DERM DP (9/7 - 9/20)'),
  ((select id from residents where sched_key='Santharam, Y'),4,'MED A'),
  ((select id from residents where sched_key='Santharam, Y'),5,'IM CONS || VACATION (10/19 - 10/23)'),
  ((select id from residents where sched_key='Santharam, Y'),6,'RHEUM CONSULTS'),
  ((select id from residents where sched_key='Santharam, Y'),7,'MED B (12/14 - 12/27) || ENDO CONSULTS-UFSC (12/28 - 1/10)'),
  ((select id from residents where sched_key='Santharam, Y'),8,'AMB (1/11 - 1/24) || AMB (1/25 - 2/7)'),
  ((select id from residents where sched_key='Santharam, Y'),9,'CCU'),
  ((select id from residents where sched_key='Santharam, Y'),10,'ID CONSULT || VACATION (3/29 - 4/2)'),
  ((select id from residents where sched_key='Santharam, Y'),11,'NF (4/5 - 4/18) || ONC CONSULT (4/19 - 5/2)'),
  ((select id from residents where sched_key='Santharam, Y'),12,'CV CONSULTS || VACATION (5/24 - 5/28)'),
  ((select id from residents where sched_key='Santharam, Y'),13,'PULM CONSULT'),
  ((select id from residents where sched_key='Scotto, T'),1,'CCU'),
  ((select id from residents where sched_key='Scotto, T'),2,'ID CONSULT'),
  ((select id from residents where sched_key='Scotto, T'),3,'CCU'),
  ((select id from residents where sched_key='Scotto, T'),4,'ENDO CONSULTS-UFSC || VACATION (10/12 - 10/16)'),
  ((select id from residents where sched_key='Scotto, T'),5,'MED D'),
  ((select id from residents where sched_key='Scotto, T'),6,'AMB (11/16 - 11/29) || ONC CONSULT (11/30 - 12/13)'),
  ((select id from residents where sched_key='Scotto, T'),7,'AMB (12/14 - 12/27) || NF (12/28 - 1/10)'),
  ((select id from residents where sched_key='Scotto, T'),8,'IM CONS || VACATION (1/25 - 1/29)'),
  ((select id from residents where sched_key='Scotto, T'),9,'NEPH CONS'),
  ((select id from residents where sched_key='Scotto, T'),10,'PALLIATIVE || VACATION (3/22 - 3/26)'),
  ((select id from residents where sched_key='Scotto, T'),11,'MED A (4/5 - 4/18) || GI CONSULT (4/19 - 5/2)'),
  ((select id from residents where sched_key='Scotto, T'),12,'PULM CONSULT'),
  ((select id from residents where sched_key='Scotto, T'),13,'RHEUM CONSULTS (5/31 - 6/13) || UF DERM DP (6/14 - 6/30)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),1,'MED C'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),2,'UF DERM DP (7/27 - 8/9) || ID CONSULT (8/10 - 8/23) || VACATION (8/17 - 8/21)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),3,'NF (8/24 - 9/6) || GI CONSULT (9/7 - 9/20)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),4,'MICU C'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),5,'AMB (10/19 - 11/1) || RHEUM CONSULTS (11/2 - 11/15) || VACATION (11/2 - 11/6)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),6,'AMB'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),7,'PULM CONSULT (12/14 - 12/27) || MED B (12/28 - 1/10)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),8,'ENDO CONSULTS-UFSC'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),9,'IM CONS'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),10,'NEPH CONS'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),11,'CV CONSULTS || VACATION (4/12 - 4/16)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),12,'NF (5/3 - 5/16) || AMB (5/17 - 5/30)'),
  ((select id from residents where sched_key='Watford, S (PRG3)'),13,'PALLIATIVE');

commit;
